name: my_cv_agent_flutter
description: AI CV Agent - Tailored Resume Matching App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  intl: ^0.18.1   # ✅ Add this line under dependencies
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_spinkit: ^5.2.0
  sqflite: ^2.3.2
  path: ^1.8.3
  google_fonts: ^6.1.0  # 🎨 Professional typography system
  
  # PDF viewer dependencies
  syncfusion_flutter_pdfviewer: ^24.2.9
  dio: ^5.4.0
  
  # Firebase dependencies - updated to latest compatible versions
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.3
  flutter_markdown: ^0.7.7+1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
