// TODO: Uncomment after running 'flutterfire configure' with your Firebase project

/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id',
    messagingSenderId: '123456789',
    projectId: 'cv-maker-demo',
    authDomain: 'cv-maker-demo.firebaseapp.com',
    storageBucket: 'cv-maker-demo.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-android-api-key',
    appId: 'demo-android-app-id',
    messagingSenderId: '123456789',
    projectId: 'cv-maker-demo',
    storageBucket: 'cv-maker-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-ios-api-key',
    appId: 'demo-ios-app-id',
    messagingSenderId: '123456789',
    projectId: 'cv-maker-demo',
    storageBucket: 'cv-maker-demo.appspot.com',
    iosBundleId: 'com.example.myCvAgentFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-macos-api-key',
    appId: 'demo-macos-app-id',
    messagingSenderId: '123456789',
    projectId: 'cv-maker-demo',
    storageBucket: 'cv-maker-demo.appspot.com',
    iosBundleId: 'com.example.myCvAgentFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-windows-api-key',
    appId: 'demo-windows-app-id',
    messagingSenderId: '123456789',
    projectId: 'cv-maker-demo',
    authDomain: 'cv-maker-demo.firebaseapp.com',
    storageBucket: 'cv-maker-demo.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}
*/
