name: Deploy to GitHub Pages

on:
  push:
    branches: [ enhanced-vps-ghs ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./mobile_app
    
    - name: Build web
      run: flutter build web --release --base-href="/cv-new/"
      working-directory: ./mobile_app
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mobile_app/build/web
