name: Deploy to GitHub Pages
# Try-2: Updated deployment workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          
      - run: flutter pub get
        working-directory: ./cv-magic-app/mobile_app
        
      - run: flutter build web --release --base-href="/cv-new/"
        working-directory: ./cv-magic-app/mobile_app
        
      - name: Create deployment directory
        run: |
          # Create a temporary deployment directory
          mkdir -p deployment
          cp -r cv-magic-app/mobile_app/build/web/* deployment/
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment